services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src

  js-server:
    build:
      context: ./js-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./js-server:/app
